name: Update Submodules

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # This runs the workflow every hour

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true  # This checks out submodules as well

      - name: Update Submodules
        run: |
          git submodule foreach '
            default_branch=$(git remote show origin | grep "HEAD branch" | cut -d ":" -f 2 | xargs)
            git config pull.rebase true
            git pull origin $default_branch
          '

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update submodules to the latest version" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
