name: Update Submodules

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0,20,40 * * * *' # This runs the workflow every hour

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Update Submodules
        run: |
          git submodule foreach '
            git config user.email "github-actions@github.com"
            git config user.name "GitHub Actions"
            git config pull.rebase true
            git pull origin master
          '

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add .
          git commit -m "Update submodules to the latest version" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
